# Generated by Django 4.2.4 on 2023-08-31 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('events_id', models.AutoField(primary_key=True, serialize=False)),
                ('events_name', models.CharField(max_length=100)),
                ('events_description', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('total_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('organizer_name', models.CharField(max_length=100)),
                ('industry_type', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('organizer_email', models.EmailField(max_length=100)),
                ('organizer_mobile_no', models.CharField(max_length=10)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_email', models.EmailField(max_length=100)),
                ('contact_person_mobile_no', models.CharField(max_length=10)),
                ('contact_person_designation', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(max_length=100)),
                ('ticket_price', models.IntegerField()),
                ('ticket_description', models.CharField(max_length=100)),
                ('total_tickets', models.IntegerField()),
                ('total_tickets_sold', models.IntegerField()),
                ('total_tickets_scanned', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.events')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.organizer'),
        ),
    ]
