# Generated by Django 4.2.4 on 2023-09-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_speakers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='organizer_id',
            new_name='organizer',
        ),
    ]
