# Generated by Django 4.2.4 on 2023-09-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_rename_organizer_id_events_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakers',
            old_name='events_id',
            new_name='events',
        ),
    ]
