# Generated by Django 4.2.4 on 2023-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_rename_events_id_speakers_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='speaker_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
