# Generated by Django 4.2.4 on 2023-08-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.UUIDField(default='edc83edc-acff-4909-a36f-ee0219360f1c', primary_key=True, serialize=False),
        ),
    ]
