# Generated by Django 4.2.4 on 2023-08-31 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.UUIDField(default='8ccbeafe-1884-4e9c-8d49-51c3696611c2', primary_key=True, serialize=False),
        ),
    ]
