# Generated by Django 4.2.4 on 2023-09-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_address_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.URLField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
